name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gcc: [9, 10, 11, 12, 13, 14]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update apt
        run: sudo apt update && sudo apt install build-essential
      - name: Install g++
        run: sudo apt install g++-${{ matrix.gcc }}
      - name: Run build
        run: g++-${{ matrix.gcc }} -std=c++20 -Wall -Wextra -O3 -march=native -I. -o ./tests/tests-${{ matrix.gcc }}.out ./tests/tests.cpp
      - name: Run tests
        run: ./tests/tests-${{matrix.gcc}}.out
