name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build
        run: g++ -std=c++20 -Wall -Wextra -O3 -march=native -I. -o ./tests/tests.out ./tests/tests.cpp
      - name: Run tests
        run: ./tests/tests.out
